<a href="https://colab.research.google.com/github/Mujthaba-GM/Zaid-repository/blob/main/Zi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Factorial of given number
def fact(n, f):
    while n != 0:
        f = f * n
        n -= 1
    return f  # return after loop ends

n = int(input('Enter n value: '))
f = 1
fa = fact(n, f)
print("Factorial of given number:", fa)



Enter n value: 4
Factorial of given number: 24


In [ ]:
#Sum of n natural numbers

def sumnat(n, sum):
    while n != 0:
        sum=sum+n
        n -= 1
    return sum  # return after loop ends

n = int(input('Enter n value: '))
sum = 0
sa = sumnat(n, sum)
print("Factorial of given number:", sa)




Enter n value: 14
Factorial of given number: 105


In [ ]:
#Multiplication of given numebr
def multable(n,i):
  while i<=10:
    print(i*n)
    i+=1

n=int(input("Enter n value  for u need Multiplication table"))
i=1
mul=multable(n,i)

Enter n value  for u need Multiplication table5
5
10
15
20
25
30
35
40
45
50


In [ ]:
#Fibonacci series
def fibonacci(n):
    a = 0
    b = 1
    print(a)
    print(b)
    c = a + b
    while c <= n:
        print(c)
        a = b
        b = c
        c = a + b  # Move this inside the loop

# Example
num = int(input("Enter max value: "))
fibonacci(num)


Enter max value: 4
0
1
1
2
3


In [ ]:
# List operations
list_int = [1, 2, 3, 4, 5]
list_float = [1.4, 2.4, 3.5]
list_char = ['a', 'b', 'c']
list_string = ['apple', "boy"]

print("Integer List:", list_int)
print("Float List:", list_float)
print("Character List:", list_char)
print("String List:", list_string)

# Slicing
print("Negative slicing (last element):", list_int[-1])
print("Integer slicing (0 to -1):", list_int[0:-1])

# Basic list operations
print("Length of list_int:", len(list_int))
print("Sum of list_int:", sum(list_int))
print("Maximum in list_int:", max(list_int))
print("Minimum in list_int:", min(list_int))

# Add elements
list_int.append(6)
print("After append(6):", list_int)

list_int.insert(2, 10)
print("After insert(2, 10):", list_int)

# Remove elements
list_int.remove(10)
print("After remove(10):", list_int)

popped = list_int.pop()
print("After pop():", list_int, "| Popped element:", popped)

# Sorting
list_int.sort()
print("Sorted list:", list_int)

# Reversing
list_int.reverse()
print("Reversed list:", list_int)



In [ ]:
# Creating tuples
numbers = (10, 20, 30, 40, 50)
fruits = ("Apple", "Banana", "Cherry")

# Printing tuples
print("Numbers tuple:", numbers)
print("Fruits tuple:", fruits)

# Accessing elements
print("First number:", numbers[0])
print("Last number:", numbers[-1])

# Slicing
print("Some numbers:", numbers[1:4])

# Concatenation
more_numbers = numbers + (60, 70)
print("Combined numbers:", more_numbers)

# Length of a tuple
print("Count of numbers:", len(numbers))

# Iterating through a tuple
print("Fruit names:")
for fruit in fruits:
    print(fruit)

# Checking membership
print("Is 30 in numbers?", 30 in numbers)

# Modifying tuple (convert to list and back)
num_list = list(numbers)
num_list.append(60)
updated_numbers = tuple(num_list)
print("Updated numbers tuple:", updated_numbers)

# Tuple unpacking
n1, n2, n3, n4, n5 = numbers
print("Unpacked values:", n1, n2, n3, n4, n5)


Numbers tuple: (10, 20, 30, 40, 50)
Fruits tuple: ('Apple', 'Banana', 'Cherry')
First number: 10
Last number: 50
Some numbers: (20, 30, 40)
Combined numbers: (10, 20, 30, 40, 50, 60, 70)
Count of numbers: 5
Fruit names:
Apple
Banana
Cherry
Is 30 in numbers? True
Updated numbers tuple: (10, 20, 30, 40, 50, 60)
Unpacked values: 10 20 30 40 50


In [ ]:
# Creating a dictionary
student = {
    "name": "John",
    "age": 20,
    "course": "Python"
}

# Printing the dictionary
print("Student details:", student)

# Accessing values
print("Name:", student["name"])
print("Age:", student["age"])

# Adding a new key-value pair
student["grade"] = "A"
print("After adding grade:", student)

# Updating a value
student["age"] = 21
print("After updating age:", student)

# Removing a key-value pair
del student["course"]
print("After removing course:", student)

# Checking if a key exists
print("Is 'name' in student?", "name" in student)

# Getting all keys and values
print("Keys:", student.keys())
print("Values:", student.values())

# Iterating over dictionary
print("All details:")
for key, value in student.items():
    print(key, ":", value)


Student details: {'name': 'John', 'age': 20, 'course': 'Python'}
Name: John
Age: 20
After adding grade: {'name': 'John', 'age': 20, 'course': 'Python', 'grade': 'A'}
After updating age: {'name': 'John', 'age': 21, 'course': 'Python', 'grade': 'A'}
After removing course: {'name': 'John', 'age': 21, 'grade': 'A'}
Is 'name' in student? True
Keys: dict_keys(['name', 'age', 'grade'])
Values: dict_values(['John', 21, 'A'])
All details:
name : John
age : 21
grade : A


In [ ]:
#Linear search
# List of numbers
numbers = [10, 20, 30, 40, 50]

# Number to search
key = 30

# Search using loop
for num in numbers:
    if num == key:
        print(key, "found")
        break
else:
    print(key, "not found")


30 found


In [ ]:
# Function to perform bubble sort
def bubble_sort(nums):
    n = len(nums)
    for i in range(n):
        for j in range(n - 1 - i):
            if nums[j] > nums[j + 1]:
                # Swap
                nums[j], nums[j + 1] = nums[j + 1], nums[j]
    return nums

# List to sort
numbers = [40, 10, 30, 50, 20]

# Call the function
sorted_numbers = bubble_sort(numbers)

# Print the sorted list
print("Sorted list:", sorted_numbers)


Sorted list: [10, 20, 30, 40, 50]


In [ ]:
#Binary search
# Sorted list of numbers
nums = [10, 20, 30, 40, 50]

# Number to search
key = 30

# Binary Search
low = 0
high = len(nums) - 1

while low <= high:
    mid = (low + high) // 2
    if nums[mid] == key:
        print(key, "found at position", mid)
        break
    elif nums[mid] < key:
        low = mid + 1
    else:
        high = mid - 1
else:
    print(key, "not found")


30 found at position 2


In [ ]:
#Binary search using functions
# Binary Search function
def binary_search(nums, key):
    low = 0
    high = len(nums) - 1

    while low <= high:
        mid = (low + high) // 2
        if nums[mid] == key:
            return mid  # Found, return position
        elif nums[mid] < key:
            low = mid + 1
        else:
            high = mid - 1

    return -1  # Not found

# Sorted list
numbers = [10, 20, 30, 40, 50]
key = 30

# Call function
result = binary_search(numbers, key)

# Show result
if result != -1:
    print(f"{key} found at position {result}")
else:
    print(f"{key} not found")


In [ ]:
#stack
# Create an empty stack
stack = []

# Function to push an item
def push(item):
    stack.append(item)
    print(item, "pushed to stack")

# Function to pop an item
def pop_item():
    if not stack:
        print("Stack is empty")
    else:
        item = stack.pop()
        print("Popped item:", item)

# Function to peek top item
def peek():
    if not stack:
        print("Stack is empty")
    else:
        print("Top item:", stack[-1])

# Function to display stack
def display():
    print("Stack:", stack)

# Test the stack operations
push(10)
push(20)
push(30)
display()
peek()
pop_item()
display()
pop_item()
display()
pop_item()
display()
pop_item()
display()





10 pushed to stack
20 pushed to stack
30 pushed to stack
Stack: [10, 20, 30]
Top item: 30
Popped item: 30
Stack: [10, 20]
Popped item: 20
Stack: [10]
Popped item: 10
Stack: []
Stack is empty
Stack: []


In [ ]:
# Create an empty queue
queue = []

# Function to add item to the queue
def enqueue(item):
    queue.append(item)
    print(item, "added to queue")

# Function to remove item from the queue
def dequeue():
    if not queue:
        print("Queue is empty")
    else:
        item = queue.pop(0)
        print("Removed item:", item)

# Function to display the queue
def display():
    print("Queue:", queue[0:])

# Function to see the front item
def front():
    if not queue:
        print("Queue is empty")
    else:
        print("Front item:", queue[0])

# Testing the queue
enqueue(10)
enqueue(20)
enqueue(30)
display()
front()
dequeue()
display()


10 added to queue
20 added to queue
30 added to queue
Queue: [10, 20, 30]
Front item: 10
Removed item: 10
Queue: [20, 30]


In [2]:
#Single Diamensional matrix operations
import numpy as np
# 1D Array Operations
print("1D ARRAY OPERATIONS")
arr1D = np.array([1, 2, 3, 4, 5])
print("Original 1D Array:", arr1D) # prints the elem of array 1D
print("Shape:", arr1D.shape)
print("Size:", arr1D.size)
print("Data Type:", arr1D.dtype)
print("Sum:", np.sum(arr1D))
print("Mean:", np.mean(arr1D))
print("Max:", np.max(arr1D))
print("Min:", np.min(arr1D))
print("Standard Deviation:", np.std(arr1D))
print("Reshaped (5,1):\n", arr1D.reshape(5,1))
print("Reversed:", arr1D[0:4])
print()


1D ARRAY OPERATIONS
Original 1D Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64
Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Reshaped (5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Reversed: [1 2 3 4]



In [3]:
#Two diamensional array operationss
import numpy as np

print("✅ 1D ARRAY OPERATIONS (Matrix form)\n")

arrA = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arrB = np.array([[4, 5, 6], [4, 5, 6], [4, 5, 6]])

print("Matrix A:\n", arrA)
print("Matrix B:\n", arrB)

# 1. Addition
print("\n1. A + B:\n", arrA + arrB)

# 2. Subtraction
print("\n2. A - B:\n", arrA - arrB)

# 3. Element-wise Multiplication
print("\n3. A * B:\n", arrA * arrB)

# 4. Matrix Multiplication (Dot product)
print("\n4. A dot B:\n", np.dot(arrA, arrB))

# 5. Transpose of A
print("\n5. Transpose of A:\n", arrA.T)

# 6. Transpose of B
print("\n6. Transpose of B:\n", arrB.T)

# 7. Sum of all elements in A
print("\n7. Sum of A:", np.sum(arrA))

# 8. Sum of elements row-wise in B
print("\n8. Row-wise sum of B:\n", np.sum(arrB, axis=1))

# 9. Sum of elements column-wise in A
print("\n9. Column-wise sum of A:\n", np.sum(arrA, axis=0))

# 10. Max of A
print("\n10. Max of A:", np.max(arrA))

# 11. Min of B
print("\n11. Min of B:", np.min(arrB))

# 12. Mean of A
print("\n12. Mean of A:", np.mean(arrA))

# 13. Standard Deviation of B
print("\n13. Standard Deviation of B:", np.std(arrB))

# 14. Square of A
print("\n14. A squared:\n", np.square(arrA))

# 15. Square root of B
print("\n15. Square root of B:\n", np.sqrt(arrB))

# 16. Diagonal of A
print("\n16. Diagonal of A:", np.diag(arrA))

# 17. Identity matrix (3x3)
print("\n17. Identity Matrix:\n", np.identity(3))

# 18. A raised to power 3 (element-wise)
print("\n18. A ** 3:\n", np.power(arrA, 3))

# 19. Cumulative sum of B
print("\n19. Cumulative sum of B:\n", np.cumsum(arrB))

# 20. Flatten matrix A
print("\n20. Flattened A:\n", arrA.flatten())

# 21. Reshape A (3x3 to 1x9)
print("\n21. Reshaped A to (1,9):\n", arrA.reshape(1, 9))

# 22. Check shape of A
print("\n22. Shape of A:", arrA.shape)

# 23. Check size of B
print("\n23. Size of B:", arrB.size)

# 24. Check data type
print("\n24. Data type of A:", arrA.dtype)

# 25. Element-wise greater than comparison
print("\n25. A > B:\n", arrA > arrB)


✅ 1D ARRAY OPERATIONS (Matrix form)

Matrix A:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Matrix B:
 [[4 5 6]
 [4 5 6]
 [4 5 6]]

1. A + B:
 [[5 7 9]
 [5 7 9]
 [5 7 9]]

2. A - B:
 [[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]

3. A * B:
 [[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]]

4. A dot B:
 [[24 30 36]
 [24 30 36]
 [24 30 36]]

5. Transpose of A:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

6. Transpose of B:
 [[4 4 4]
 [5 5 5]
 [6 6 6]]

7. Sum of A: 18

8. Row-wise sum of B:
 [15 15 15]

9. Column-wise sum of A:
 [3 6 9]

10. Max of A: 3

11. Min of B: 4

12. Mean of A: 2.0

13. Standard Deviation of B: 0.816496580927726

14. A squared:
 [[1 4 9]
 [1 4 9]
 [1 4 9]]

15. Square root of B:
 [[2.         2.23606798 2.44948974]
 [2.         2.23606798 2.44948974]
 [2.         2.23606798 2.44948974]]

16. Diagonal of A: [1 2 3]

17. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

18. A ** 3:
 [[ 1  8 27]
 [ 1  8 27]
 [ 1  8 27]]

19. Cumulative sum of B:
 [ 4  9 15 19 24 30 34 39 45]

20. Flattened A:
 [1 2 3 1 2 3 1 2 

In [6]:
#Creation of Data Frames
import pandas as pd  # Step 1: Import pandas

# Step 2: Create a simple dictionary (like a table)
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 22],
    "City": ["New York", "London", "Paris"]
}

# Step 3: Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Step 4: Display the DataFrame
print("📋 Original DataFrame:")
print(df)

# Step 5: Access a column
print("\n🔍 Access 'Name' column:")
print(df["Name"])

# Step 6: Add a new column
df["Score"] = [85, 90, 88]
print("\n➕ DataFrame after adding 'Score':")
print(df)

# Step 7: Filter rows (Age > 23)
print("\n🔎 Filter rows where Age > 23:")
print(df[df["Age"] > 23])

# Step 8: Show basic statistics
print("\n📊 Statistics of numerical columns:")
print(df.describe())
print("head\n",df.head())
print("Tail\n",df.tail())



📋 Original DataFrame:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris

🔍 Access 'Name' column:
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

➕ DataFrame after adding 'Score':
      Name  Age      City  Score
0    Alice   25  New York     85
1      Bob   30    London     90
2  Charlie   22     Paris     88

🔎 Filter rows where Age > 23:
    Name  Age      City  Score
0  Alice   25  New York     85
1    Bob   30    London     90

📊 Statistics of numerical columns:
             Age      Score
count   3.000000   3.000000
mean   25.666667  87.666667
std     4.041452   2.516611
min    22.000000  85.000000
25%    23.500000  86.500000
50%    25.000000  88.000000
75%    27.500000  89.000000
max    30.000000  90.000000
head
       Name  Age      City  Score
0    Alice   25  New York     85
1      Bob   30    London     90
2  Charlie   22     Paris     88
Tail
       Name  Age      City  Score
0    Alice   25  New York   

In [7]:
#Data pre processing operations
import pandas as pd

# Step 1: Create messy data
data = {
    "Name": ["Alice", "Bob", None, "David", "Eve"],
    "Age": [25, 30, 22, None, 29],
    "City": ["New York", "London", "Paris", "London", None],
    "Score": [85, 90, None, 88, 95]
}

# Step 2: Create the DataFrame
df = pd.DataFrame(data)
print("📋 Original DataFrame:\n", df)

# Step 3: Check for missing values
print("\n🔍 Missing Values Check:\n", df.isnull())

# Step 4: Drop rows with missing values (optional preview)
df_cleaned = df.dropna()
print("\n🧹 DataFrame after dropping rows with missing values:\n", df_cleaned)

# Step 5: Fill missing values (safe syntax, no inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Score"] = df["Score"].fillna(df["Score"].mean())
df["Name"] = df["Name"].fillna("Unknown")
df["City"] = df["City"].fillna("Unknown")

print("\n🛠️ DataFrame after filling missing values:\n", df)

# Step 6: Remove duplicate rows
df = df.drop_duplicates()
print("\n❎ DataFrame after removing duplicates:\n", df)

# Step 7: Convert data types
df["Age"] = df["Age"].astype(int)
print("\n🔄 DataFrame after converting 'Age' to integer:\n", df)


📋 Original DataFrame:
     Name   Age      City  Score
0  Alice  25.0  New York   85.0
1    Bob  30.0    London   90.0
2   None  22.0     Paris    NaN
3  David   NaN    London   88.0
4    Eve  29.0      None   95.0

🔍 Missing Values Check:
     Name    Age   City  Score
0  False  False  False  False
1  False  False  False  False
2   True  False  False   True
3  False   True  False  False
4  False  False   True  False

🧹 DataFrame after dropping rows with missing values:
     Name   Age      City  Score
0  Alice  25.0  New York   85.0
1    Bob  30.0    London   90.0

🛠️ DataFrame after filling missing values:
       Name   Age      City  Score
0    Alice  25.0  New York   85.0
1      Bob  30.0    London   90.0
2  Unknown  22.0     Paris   89.5
3    David  26.5    London   88.0
4      Eve  29.0   Unknown   95.0

❎ DataFrame after removing duplicates:
       Name   Age      City  Score
0    Alice  25.0  New York   85.0
1      Bob  30.0    London   90.0
2  Unknown  22.0     Paris   89.5
3 